name: 构建docker镜像
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取最新代码
        uses: actions/checkout@master
      - name: 登录到DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 构建镜像
        run: |
          docker build -t wangjin252/video-recorder:1.0 .
          docker push wangjin252/video-recorder:1.0
